sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.8.4
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
  
install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - |
    curl -sSL https://get.haskellstack.org/ | sh
    stack --version
    stack build --system-ghc \
          --test --no-run-tests \
          --ghc-options=-Werror

script:
  - >-
    stack test --system-ghc
