resolver: lts-18.13
extra-deps:
  - hslua-2.0.0
  - hslua-classes-2.0.0
  - hslua-core-2.0.0
  - hslua-marshalling-2.0.0
  - hslua-objectorientation-2.0.0
  - hslua-packaging-2.0.0
  - lua-2.0.0
  - tasty-lua-1.0.0
