name: CI

# Trigger the workflow on push or pull request, but only for the
# master branch
on:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - 'stack.yaml'
      - '.github/FUNDING.yml'

jobs:
  build:
    name: ghc ${{ matrix.versions.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - ghc: '8.4.4'
            cabal: '2.4'
          - ghc: '8.6.5'
            cabal: '3.2'
          - ghc: '8.8.4'
            cabal: '3.2'
          - ghc: '8.10.7'
            cabal: '3.2'
          - ghc: '9.0.2'
            cabal: '3.4'
          - ghc: '9.2.6'
            cabal: '3.6'
          - ghc: '9.4.4'
            cabal: '3.8'

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.versions.ghc }}
        cabal-version: ${{ matrix.versions.cabal }}

    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-cabal

    - name: Build
      run: |
        cabal v2-build --enable-tests

    - name: Test
      run: |
        cabal v2-test --enable-tests
